CREATE TABLE IF NOT EXISTS servers (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
